# Generated by Django 5.1.3 on 2024-11-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('high_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('average_value', models.DecimalField(decimal_places=10, max_digits=20)),
                ('absolute_volatility', models.DecimalField(decimal_places=10, max_digits=20)),
                ('percentage_volatility_open', models.DecimalField(decimal_places=10, max_digits=20)),
                ('percentage_volatility_low', models.DecimalField(decimal_places=10, max_digits=20)),
                ('close_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('number_of_changes', models.IntegerField()),
                ('max_delay', models.DecimalField(decimal_places=10, max_digits=20)),
                ('min_delay', models.DecimalField(decimal_places=10, max_digits=20)),
                ('average_delay', models.DecimalField(decimal_places=10, max_digits=20)),
                ('volume_start', models.DecimalField(decimal_places=10, max_digits=20)),
                ('volume_stop', models.DecimalField(decimal_places=10, max_digits=20)),
                ('volume_delta', models.DecimalField(decimal_places=10, max_digits=20)),
                ('volume_percent_change', models.DecimalField(decimal_places=10, max_digits=20)),
                ('volume_average_per_minute', models.DecimalField(decimal_places=10, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
