# Generated by Django 5.1.3 on 2024-11-11 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_parserlock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParserLock',
        ),
    ]
